name = "GT6: Modernized"
author = "Agent"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40addf8798915b8f565d3eecb0e2d0c11eb75ec54a1c29f8c2560f2d17b7e6ce"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7", "1.7.10"]
